# Delay to spam the register/login message
spam_each_seconds: 1

# After how much seconds should we drop the player
kick_at_seconds: 20

# Settings for when the player is logging in / registering
allowOtherCommands: false
allowMovement: false
allowChat: false
allowInventoryInteraction: false

# Max accounts allowed per IP addressalready_registered
max_accounts_allowed: 2

# Should we teleport the player every time to the set spawn or not
forceSpawnTeleport: true

# All configurable messages
messages:
  register_message: "&eYou have to register before playing into our server! /register <password> <confirmPassword>"
  login_message: "&eYou have to login. /login <password>"
  time_exceeded: "&cTime to login/register expired!"
  have_to_login: "&cYou have to login first before using that!"
  have_to_register: "&cYou have to register first before using that!"
  have_to_be_logged_in: "&cYou have to be logged in first before using that!"
  already_logged_in: "&cYou have already logged in"
  invalid_login_usage: "&cInvalid login usage! /login <password>"
  have_to_register_first: "&cYou have to register first before logging in!"
  wrong_password: "&cWrong password!"
  login_successful: "&aLogged in successfully"
  max_accounts_exceeded: "&cYou cannot register this accounts. You already have the maximum accounts allowed!"
  invalid_register_usage: "&cInvalid register usage! /register <password> <confirmPassword>"
  invalid_confirmation: "&cPassword mismatch! /register <password> <confirmPassword>"
  register_successful: "&aYou have registered successfully!"
  unregister_successful: "&aYou have unregistered your account successfully!"
  already_registered: "&cYou are already registered"
  invalid_unregister_usage: "&cInvalid usage! /unregister <password>"
